vaadin.launch-browser=true
spring.application.name=moveinsa
spring.jpa.hibernate.ddl-auto=update

# Correct the JDBC URL format
spring.datasource.url=jdbc:mysql://avnadmin:AVNS_VS5FxkObZnKBiowyOSl@mysql-moveinsa-moveinsa.l.aivencloud.com:16227/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_VS5FxkObZnKBiowyOSl
spring.datasource.oracleucp.port-number=16227
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Ensure initialization is properly managed
spring.jpa.defer-datasource-initialization=true
spring.main.lazy-initialization=true
